Repository apache/pulsar-client-go, pull requests merged in 2019-11, with the labels that each got.

#84 Fixed locking between connection_reader and connection
  pulsar/impl_partition_consumer.go
  pulsar/internal/connection.go
  pulsar/internal/connection_reader.go
Labels: type/bug

#82 Added a message id tracker for acking messages that are batched.
  pulsar/impl_message.go
  pulsar/impl_message_test.go
  pulsar/message.go
Labels: area/consumer

#92 [ISSUE #87] Ensure all producer partitions are closed.
  pulsar/impl_producer.go
Labels: type/bug

#95 Fixed RpcClient.RequestOnCnxNoWait() to not require a request id
  pulsar/consumer_partition.go
  pulsar/internal/commands.go
  pulsar/internal/commands_test.go
  pulsar/internal/connection.go
  pulsar/internal/lookup_service_test.go
  pulsar/internal/rpc_client.go
Labels: type/enhancement

#99 Remove error return on Close() methods
  pulsar/client.go
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/consumer_test.go
  pulsar/impl_client.go
  pulsar/impl_client_test.go
  pulsar/impl_partition_producer.go
  pulsar/impl_producer.go
  pulsar/internal/closable.go
  pulsar/producer.go
  pulsar/producer_test.go
  pulsar/reader.go
Labels: type/enhancement

#102 Updated zstd go library to avoid cgo dependency for compression
  go.mod
  go.sum
  pkg/compression/zstd.go
  pkg/compression/zstd_native.go
Labels: type/enhancement

#105 [Producer] Set error only if not nil
  pulsar/impl_producer.go
Labels: type/bug
