Repository apache/pulsar-client-go, pull requests merged in 2019-12, with the labels that each got.

#119 [Issue 118][client_impl.go] fix race condition when accessing client.handlers
  pulsar/client_impl.go
  pulsar/internal/client_handlers.go
  pulsar/internal/client_handlers_test.go
Labels: type/bug

#131 Fixed detection and handling of stale connections
  pulsar/internal/connection.go
  pulsar/internal/connection_reader.go
  pulsar/producer_partition.go
Labels: type/bug

#132 Move pkg stuff under pulsar/internal
  integration-tests/license_test.go
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/helper.go
  pulsar/impl_message.go
  pulsar/internal/auth/disabled.go
  pulsar/internal/auth/provider.go
  pulsar/internal/auth/tls.go
  pulsar/internal/auth/token.go
  pulsar/internal/batch_builder.go
  pulsar/internal/commands.go
  pulsar/internal/compression/compression.go
  pulsar/internal/compression/compression_test.go
  pulsar/internal/compression/lz4.go
  pulsar/internal/compression/noop.go
  pulsar/internal/compression/zlib.go
  pulsar/internal/compression/zstd.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
  pulsar/internal/connection_reader.go
  pulsar/internal/lookup_service.go
  pulsar/internal/lookup_service_test.go
  pulsar/internal/pb/PulsarApi.pb.go
  pulsar/internal/rpc_client.go
  pulsar/producer_partition.go
Labels: type/enhancement, type/task

#133 Removed unused config options
  perf/perf-producer.go
  pulsar/client.go
  pulsar/consumer.go
  pulsar/consumer_test.go
  pulsar/producer.go
  pulsar/producer_test.go
Labels: type/task

#130 Allow to specify a function that supply a token
  pulsar/client.go
  pulsar/client_impl_test.go
  pulsar/internal/auth/token.go
Labels: type/enhancement

#136 Removed SendTimeout from producer options
  perf/perf-producer.go
  pulsar/producer.go
Labels: type/cleanup

#137 Use the specified connection timeout when creating connections
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
Labels: type/bug

#139 Implemented the operation timeout check
  pulsar/client_impl.go
  pulsar/internal/rpc_client.go
Labels: type/task

#141 Make producer.Send() to also return MessageID
  examples/producer/producer.go
  pulsar/consumer_regex_test.go
  pulsar/consumer_test.go
  pulsar/producer.go
  pulsar/producer_impl.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: type/enhancement
