Repository apache/pulsar-client-go, pull requests merged in 2019-10, with the labels that each got.

#70 [refactor] clean code
  pulsar/consumer_test.go
  pulsar/impl_client.go
  pulsar/internal/connection.go
Labels: type/enhancement

#73 [ISSUE #64]fix: avoid assert panic
  pulsar/impl_partition_producer.go
Labels: area/producer, type/bug

#77 [ISSUE #72] Fix data race conditions.
  license_test.go
  pulsar/impl_consumer.go
  pulsar/impl_partition_producer.go
  pulsar/internal/connection.go
  pulsar/unacked_msg_tracker.go
  pulsar/unacked_msg_tracker_test.go
Labels: type/bug
