Repository apache/pulsar-client-go, pull requests merged in 2020-07, with the labels that each got.

#305 [Issue 304][Reader] fixed panic in CreateReader API using custom MessageID for ReaderOptions
  pulsar/reader_impl.go
  pulsar/reader_test.go
Labels: area/reader

#312 Fix CompressMaxSize() for ZLib provider
  pulsar/internal/compression/zlib.go
Labels: type/bug

#316 Reduce the size of the MessageID structs by one word on 64-bit arch
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/impl_message.go
  pulsar/impl_message_test.go
  pulsar/producer_partition.go
Labels: type/enhancement

#310 Share buffer pool across all partitions
  perf/perf-producer.go
  pulsar/internal/batch_builder.go
  pulsar/producer_partition.go
Labels: type/enhancement

#319 Do not allocate MessageIDs on the heap
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/consumer_regex.go
  pulsar/impl_message.go
  pulsar/impl_message_test.go
  pulsar/negative_acks_tracker.go
  pulsar/negative_acks_tracker_test.go
  pulsar/producer_test.go
  pulsar/reader_impl.go
Labels: performance, type/enhancement

#317 Export client metrics to Prometheus
  go.mod
  go.sum
  perf/pulsar-perf-go.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_regex.go
  pulsar/impl_message.go
  pulsar/internal/connection.go
  pulsar/internal/lookup_service.go
  pulsar/internal/rpc_client.go
  pulsar/producer_impl.go
  pulsar/producer_partition.go
  pulsar/reader_impl.go
Labels: type/enhancement

#313 Support oauth2 authentication for pulsar-client-go
  go.mod
  go.sum
  oauth2/auth.go
  oauth2/auth_suite_test.go
  oauth2/authorization_tokenretriever.go
  oauth2/authorization_tokenretriever_test.go
  oauth2/cache/cache.go
  oauth2/client_credentials_flow.go
  oauth2/client_credentials_flow_test.go
  oauth2/client_credentials_provider.go
  oauth2/clock/clock.go
  oauth2/clock/testing/fake_clock.go
  oauth2/config_tokenprovider.go
  oauth2/config_tokenprovider_test.go
  oauth2/device_code_flow.go
  oauth2/device_code_flow_test.go
  oauth2/device_code_provider.go
  oauth2/go.mod
  oauth2/go.sum
  oauth2/oidc_endpoint_provider.go
  oauth2/oidc_endpoint_provider_test.go
  oauth2/store/keyring.go
  oauth2/store/memory.go
  oauth2/store/store.go
  pulsar/client.go
  pulsar/client_impl_test.go
  pulsar/internal/auth/oauth2.go
  pulsar/internal/auth/oauth2_test.go
  pulsar/internal/auth/token.go
Labels: area/security, doc-required

#326 Fix producer block
  pulsar/consumer_partition.go
  pulsar/internal/connection.go
  pulsar/producer_partition.go
Labels: type/bug

#324 Different MessageID implementations for message Production and Consumption
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/consumer_regex.go
  pulsar/impl_message.go
  pulsar/impl_message_bench_test.go
  pulsar/impl_message_test.go
  pulsar/producer_test.go
  pulsar/reader_impl.go
Labels: type/enhancement

#336 [Issue 335]Fix producer state by reconnecting when receiving unexpected receipts…
  pulsar/producer_partition.go
Labels: type/bug

#337 Avoid producer deadlock on connection closing
  pulsar/internal/connection.go
Labels: type/bug
