Repository apache/pulsar-client-go, pull requests merged in 2020-02, with the labels that each got.

#179 [Issue:178]Fix concurrent map read and map write
  pulsar/internal/connection.go
Labels: type/bug

#180 Add seek by time on consumer
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_regex.go
  pulsar/consumer_test.go
  pulsar/internal/utils.go
  pulsar/internal/utils_test.go
Labels: area/consumer, type/feature

#182 Fix nil pointer dereference of PartitionMetadataResponse
  pulsar/client_impl.go
Labels: type/bug

#184 Dead letter queue implementation
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_regex.go
  pulsar/consumer_regex_test.go
  pulsar/consumer_test.go
  pulsar/dlq_router.go
  pulsar/impl_message.go
  pulsar/reader_impl.go
Labels: type/feature

#186 Expose EventTime consistently as a non-pointer
  pulsar/consumer_test.go
  pulsar/dlq_router.go
  pulsar/message.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: type/enhancement
