Repository apache/pulsar-client-go, pull requests merged in 2020-01, with the labels that each got.

#161 Fixed the connection pool logic
  pulsar/consumer_partition.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
  pulsar/internal/lookup_service.go
  pulsar/internal/lookup_service_test.go
  pulsar/internal/rpc_client.go
  pulsar/producer_partition.go
Labels: type/bug

#162 Avoid double cnx close notification on graceful server side close
  pulsar/internal/connection.go
Labels: type/bug

#163 Fixed reading from connection
  pulsar/internal/connection_reader.go
Labels: type/bug

#160 Set delay delivery when publishing a message
  pulsar/internal/batch_builder.go
  pulsar/message.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: type/feature

#165 Fixed memory leak of connection
  pulsar/internal/connection_pool.go
Labels: type/bug

#158 Topic reader implementation
  examples/reader/reader.go
  pulsar/client_impl.go
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/impl_message.go
  pulsar/internal/commands.go
  pulsar/reader.go
  pulsar/reader_impl.go
  pulsar/reader_test.go
Labels: type/feature

#157 Add retry logic when get connection error
  .gitignore
  pulsar/internal/connection_reader.go
  pulsar/internal/rpc_client.go
Labels: type/enhancement, type/feature

#167 res channel causes connection.Run() to block When request timeout occuers
  pulsar/internal/rpc_client.go
Labels: type/bug

#175 Fix partition key not set in batch builder
  pulsar/consumer_test.go
  pulsar/internal/batch_builder.go
  pulsar/producer_partition.go
Labels: type/bug

#176 PIP-55: Refresh auth credentials
  pulsar/internal/commands.go
  pulsar/internal/connection.go
  pulsar/internal/pb/PulsarApi.pb.go
Labels: type/feature
