Repository apache/pulsar-client-go, pull requests merged in 2020-04, with the labels that each got.

#209 Fixed batching flag logic
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: type/bug

#216 Use .asf.yaml to configure github repo
  .asf.yaml
Labels: area/documentation

#220 Fixed tls connection issue
  pulsar/client_impl.go
  pulsar/internal/lookup_service.go
  pulsar/internal/lookup_service_test.go
Labels: type/bug

#221 Auto update the client to handle changes in number of partitions
  pulsar/consumer_impl.go
  pulsar/consumer_regex.go
  pulsar/consumer_test.go
  pulsar/producer_impl.go
  pulsar/producer_test.go
  pulsar/test_helper.go
Labels: type/enhancement

#230 Removed unnecessary flush in sync Send() operation
  pulsar/producer_partition.go
Labels: type/enhancement

#229 Fixed race condition in producer Flush() operation
  pulsar/producer_partition.go
Labels: type/bug
