Repository apache/pulsar-client-go, pull requests merged in 2020-12, with the labels that each got.

#400 [Issue 172] Add key based batcher
  go.mod
  pulsar/batcher_builder.go
  pulsar/consumer_test.go
  pulsar/internal/batch_builder.go
  pulsar/internal/key_based_batch_builder.go
  pulsar/producer.go
  pulsar/producer_partition.go
Labels: area/producer

#408 Read the clock fewer times during message routing
  pulsar/default_router.go
  pulsar/default_router_bench_test.go
  pulsar/default_router_test.go
Labels: type/enhancement

#410 Attach topic and custom labels to Prometheus metrics
  oauth2/cache/cache.go
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/consumer_regex.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
  pulsar/internal/lookup_service.go
  pulsar/internal/lookup_service_test.go
  pulsar/internal/metrics.go
  pulsar/internal/rpc_client.go
  pulsar/internal/topic_name.go
  pulsar/internal/topic_name_test.go
  pulsar/metrics.go
  pulsar/producer_impl.go
  pulsar/producer_partition.go
  pulsar/reader_impl.go
Labels: type/feature

#415 Reduce the default TCP connection timeout from 30 to 5 seconds
  pulsar/client.go
  pulsar/client_impl.go
Labels: type/enhancement

#414 Fixed logic to attempt reconnections to same broker
  pulsar/internal/rpc_client.go
Labels: type/bug

#413 Fix discard unacked messages
  pulsar/consumer_partition.go
Labels: type/bug

#417 Renamed Metrics.RpcRequestCount to RPCRequestCount to conform to style check
  pulsar/internal/metrics.go
  pulsar/internal/rpc_client.go
Labels: area/build

#418 fix leaked nack tracker goroutine
  pulsar/consumer_partition.go
  pulsar/negative_acks_tracker.go
  pulsar/negative_acks_tracker_test.go
Labels: type/bug
