Repository apache/pulsar-client-go, pull requests merged in 2020-03, with the labels that each got.

#199 [Bug fix] Fix seek by time error
  pulsar/consumer_partition.go
Labels: area/consumer, type/bug

#205 Fix Go Producer produce to only one partition
  pulsar/consumer_test.go
  pulsar/internal/default_router.go
  pulsar/internal/default_router_test.go
  pulsar/producer_impl.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
  pulsar/test_helper.go
Labels: type/bug

#203 Add changelog file to project
  CHANGELOG.md
Labels: area/documentation
