Repository apache/pulsar-client-go, pull requests merged in 2020-08, with the labels that each got.

#343 Support specified the oauth2 private key with prefix 'file://' and 'data://'
  oauth2/client_credentials_provider.go
  pulsar/internal/auth/oauth2_test.go
Labels: type/enhancement

#347 [Issue 345] Add a new method to create auth provider from tls cert supplier
  pulsar/client.go
  pulsar/client_impl_test.go
  pulsar/internal/auth/tls.go
Labels: area/security

#329 [ISSUE-328] gets last message when LatestMessageID and inclusive
  pulsar/consumer_partition.go
  pulsar/reader_test.go
Labels: area/reader
