Repository apache/pulsar-client-go, pull requests merged in 2020-06, with the labels that each got.

#276 Allow to have multiple connections per broker
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/internal/connection_pool.go
Labels: type/enhancement

#277 Increase writeRequestsCh channel buffer size
  pulsar/internal/connection.go
Labels: type/enhancement

#280 Expose BatchingMaxSize from ProducerOptions
  pulsar/internal/batch_builder.go
  pulsar/producer.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: type/enhancement

#283 [Issue #282] Fix unable to close consumer after unsubscribe in Shared Subscription
  pulsar/consumer_partition.go
Labels: type/bug

#285 Use maxPendingMessages for sizing producer eventsChan
  pulsar/producer_partition.go
Labels: type/enhancement

#284 Introduced lifecycle for compression providers
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/internal/batch_builder.go
  pulsar/internal/compression/compression.go
  pulsar/internal/compression/compression_bench_test.go
  pulsar/internal/compression/compression_test.go
  pulsar/internal/compression/lz4.go
  pulsar/internal/compression/noop.go
  pulsar/internal/compression/zlib.go
  pulsar/internal/compression/zstd.go
  pulsar/internal/compression/zstd_cgo.go
  pulsar/internal/compression/zstd_go.go
  pulsar/producer_partition.go
Labels: type/enhancement

#286 Avoid contention on producer mutex on critical path
  pulsar/producer_impl.go
Labels: performance

#287 Switched to DataDog zstd wrapper, reusing the compression ctx
  go.mod
  go.sum
  pulsar/internal/compression/zstd_cgo.go
Labels: area/build, performance

#290 Allow applications to configure the compression level
  pulsar/consumer_partition.go
  pulsar/internal/batch_builder.go
  pulsar/internal/compression/compression.go
  pulsar/internal/compression/compression_bench_test.go
  pulsar/internal/compression/compression_test.go
  pulsar/internal/compression/zstd.go
  pulsar/internal/compression/zstd_cgo.go
  pulsar/internal/compression/zstd_go.go
  pulsar/producer.go
  pulsar/producer_partition.go
Labels: type/enhancement

#292 Used pooled buffering for compression and batch serialization
  pulsar/client_impl_test.go
  pulsar/consumer_partition.go
  pulsar/internal/batch_builder.go
  pulsar/internal/buffer.go
  pulsar/internal/commands.go
  pulsar/internal/compression/compression.go
  pulsar/internal/compression/compression_bench_test.go
  pulsar/internal/compression/compression_test.go
  pulsar/internal/compression/lz4.go
  pulsar/internal/compression/noop.go
  pulsar/internal/compression/zlib.go
  pulsar/internal/compression/zstd_cgo.go
  pulsar/internal/compression/zstd_go.go
  pulsar/internal/connection.go
  pulsar/producer_partition.go
Labels: performance

#294 Use gogofast to have in-place protobuf serialization
  go.mod
  go.sum
  integration-tests/license_test.go
  pulsar/client_impl.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/helper.go
  pulsar/impl_message.go
  pulsar/internal/batch_builder.go
  pulsar/internal/commands.go
  pulsar/internal/connection.go
  pulsar/internal/connection_reader.go
  pulsar/internal/lookup_service.go
  pulsar/internal/lookup_service_test.go
  pulsar/internal/pb/PulsarApi.pb.go
  pulsar/internal/pulsar_proto/PulsarApi.pb.go
  pulsar/internal/pulsar_proto/PulsarApi.proto
  pulsar/internal/pulsar_proto/README.md
  pulsar/internal/rpc_client.go
  pulsar/producer_partition.go
Labels: performance, type/enhancement

#298 Added semaphore implementation with lower contention
  pulsar/internal/semaphore.go
  pulsar/internal/semaphore_test.go
  pulsar/producer_partition.go
Labels: performance, type/enhancement

#300 Fixed pooled buffer lifecycle
  pulsar/internal/batch_builder.go
  pulsar/internal/connection.go
  pulsar/producer_partition.go
Labels: type/bug

#301 Removed blocking queue iterator
  pulsar/internal/blocking_queue.go
  pulsar/internal/blocking_queue_test.go
  pulsar/producer_partition.go
Labels: type/enhancement
