Repository apache/pulsar-client-go, pull requests merged in 2021-05, with the labels that each got.

#487 [fix #479] use pulsar-test-infra/pulsarbot as github action bot
  .github/workflows/bot.yml
Labels: area/build

#514 Make PartitionsAutoDiscoveryInterval configurable
  pulsar/consumer_test.go
  pulsar/producer.go
  pulsar/producer_impl.go
Labels: type/enhancement

#521 Always check connection close channell, before attempting to put requests
  pulsar/internal/connection.go
Labels: type/bug

#523 Update changelog to 0.5.0
  CHANGELOG.md
  VERSION
  stable.txt
Labels: area/documentation

#524 update jwt-go dependency to resolve vulnerabilities
  go.sum
  oauth2/auth.go
  oauth2/go.mod
  oauth2/go.sum
Labels: area/security

#522 Fixed Athenz repository name
  go.mod
  go.sum
  pulsar/internal/auth/athenz.go
  pulsar/internal/auth/athenz_test.go
Labels: area/build

#525 [bug] Fix reader latest position
  pulsar/consumer_partition.go
  pulsar/impl_message.go
  pulsar/message.go
Labels: type/bug
