Repository apache/pulsar-client-go, pull requests merged in 2022-02, with the labels that each got.

#721 [Bugfix] producer runEventsLoop for reconnect early exit
  pulsar/consumer_partition.go
  pulsar/internal/connection_pool.go
  pulsar/producer_partition.go
Labels: type/bug

#719 [issue 679][oauth2] Fix macos compiler warnings
  go.sum
  oauth2/go.mod
  oauth2/go.sum
Labels: area/build

#730 [Issue 729]stop ticker when create producer failed
  pulsar/producer_partition.go
Labels: type/bug

#740 Upgrade klauspost/compress to v1.14.4
  go.mod
  go.sum
Labels: type/enhancement

#738 Upgrade prometheus client to 1.11.1
  go.mod
  go.sum
Labels: area/security
