Repository apache/pulsar-client-go, pull requests merged in 2022-09, with the labels that each got.

#838 Make keepalive interval configurable
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
Labels: type/enhancement

#809 [issue #807] dlq topic producer options
  pulsar/consumer.go
  pulsar/consumer_test.go
  pulsar/dlq_router.go
  pulsar/retry_router.go
Labels: area/producer, area/consumer, type/bug

#843 [bugfix] Fix wrong check eventime by default
  pulsar/consumer_test.go
  pulsar/message_test.go
  pulsar/producer_partition.go
Labels: type/bug

#853 Parameterize the reconnection option
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/dlq_router.go
  pulsar/internal/backoff.go
  pulsar/internal/backoff_test.go
  pulsar/internal/http_client.go
  pulsar/internal/rpc_client.go
  pulsar/negative_backoff_policy.go
  pulsar/producer.go
  pulsar/producer_partition.go
  pulsar/retry_router.go
Labels: type/enhancement
