Repository apache/pulsar-client-go, pull requests merged in 2022-05, with the labels that each got.

#750 [Issue 749]Fix panic caused by flushing current batch with an incorrect internal function.
  pulsar/producer_partition.go
Labels: type/bug

#772 Add consumer state check when request commands
  pulsar/consumer_partition.go
Labels: area/consumer, type/enhancement

#775 Add error response for Ack func
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_regex.go
  pulsar/impl_message.go
  pulsar/internal/connection_pool.go
  pulsar/internal/pulsartracing/consumer_interceptor_test.go
Labels: type/bug

#767 Revert "Fix stuck when reconnect broker (#703)"
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
Labels: type/bug

#776 Support ack response for Go SDK
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/consumer_test.go
  pulsar/internal/connection.go
Labels: type/feature

#780 [Issue 779]Fix ack request not set requestId when enable AckWithResponse option
  pulsar/consumer_partition.go
Labels: type/bug
