Repository apache/pulsar-client-go, pull requests merged in 2022-03, with the labels that each got.

#747 Temporarily point ci to pulsar 2.8.2
  Dockerfile
Labels: area/build

#751 [build] make go version consistent
  Dockerfile
Labels: area/build

#741 Add schema support to Reader
  pulsar/reader.go
  pulsar/reader_impl.go
  pulsar/reader_test.go
Labels: type/enhancement

#743 Add TableView support
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/table_view.go
  pulsar/table_view_impl.go
  pulsar/table_view_test.go
Labels: type/feature
