Repository apache/pulsar-client-go, pull requests merged in 2023-03, with the labels that each got.

#955 [feat] Support memory limit for producer.
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/error.go
  pulsar/internal/channel_cond.go
  pulsar/internal/channel_cond_test.go
  pulsar/internal/memory_limit_controller.go
  pulsar/internal/memory_limit_controller_test.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
Labels: area/producer, type/enhancement

#968 Optimize the performance by passing MessageID implementations by pointers
  pulsar/ack_grouping_tracker_test.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/consumer_regex.go
  pulsar/consumer_test.go
  pulsar/impl_message.go
  pulsar/impl_message_bench_test.go
  pulsar/impl_message_test.go
  pulsar/message_chunking_test.go
  pulsar/negative_acks_tracker.go
  pulsar/negative_acks_tracker_test.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
  pulsar/reader_impl.go
Labels: type/enhancement

#974 Fix nack backoff policy logic
  pulsar/consumer_impl.go
Labels: type/bug

#963 [PIP-165] Auto release idle connections
  pulsar/client.go
  pulsar/client_impl.go
  pulsar/client_impl_test.go
  pulsar/internal/connection.go
  pulsar/internal/connection_pool.go
  pulsar/internal/helper.go
Labels: type/feature

#960 [improve] Athenz auth provider supports Copper Argos
  pulsar/auth/athenz.go
  pulsar/auth/athenz_test.go
Labels: type/enhancement, doc-required, area/security

#981 [fix] Fix data race in checkAndCleanIdleConnections
  pulsar/internal/connection_pool.go
Labels: type/bug

#986 Fix ack grouping tracker is duplicate method will be blocked.
  pulsar/ack_grouping_tracker.go
  pulsar/ack_grouping_tracker_test.go
Labels: type/bug

#987 [feat] Expose the chunk config of consumer to the reader
  pulsar/reader.go
  pulsar/reader_impl.go
  pulsar/reader_test.go
Labels: type/enhancement

#988 Optimize batch index ACK performance
  pulsar/ack_grouping_tracker.go
  pulsar/ack_grouping_tracker_test.go
  pulsar/consumer_partition.go
  pulsar/consumer_partition_test.go
  pulsar/message.go
Labels: performance

#994 Fix batched messages not ACKed correctly when batch index ACK is disabled
  pulsar/consumer_partition.go
  pulsar/consumer_test.go
Labels: type/bug

#991 [feat] Support consumer client memory limit
  pulsar/client_impl.go
  pulsar/consumer_partition.go
  pulsar/consumer_test.go
  pulsar/impl_message.go
  pulsar/internal/memory_limit_controller.go
  pulsar/internal/memory_limit_controller_test.go
Labels: type/feature
