Repository apache/pulsar-client-go, pull requests merged in 2024-02, with the labels that each got.

#1164 Fix SIGSEGV with zstd compression enabled
  pulsar/internal/compression/zstd_cgo.go
  pulsar/internal/utils.go
  pulsar/producer_test.go
Labels: type/bug, release/0.12.1

#1165 [Producer] respect context cancellation in Flush
  pulsar/consumer_test.go
  pulsar/internal/pulsartracing/producer_interceptor_test.go
  pulsar/producer.go
  pulsar/producer_impl.go
  pulsar/producer_partition.go
  pulsar/producer_test.go
  pulsar/reader_test.go
Labels: type/enhancement

#1173 Fix BytesSchema
  pulsar/schema.go
  pulsar/schema_test.go
  pulsar/table_view_test.go
Labels: type/bug

#1178 [feat] Support partitioned topic reader
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_partition.go
  pulsar/reader.go
  pulsar/reader_impl.go
  pulsar/reader_test.go
Labels: release/0.12.1

#1181 [Bug Fix]Fix available permits in MessageReceived
  pulsar/consumer_partition.go
Labels: type/bug

#1182 [fix] Fix Infinite Loop in Reader's `HasNext` Function
  pulsar/client_impl.go
  pulsar/consumer_partition.go
  pulsar/reader.go
  pulsar/reader_test.go
Labels: type/bug, release/0.12.1
