Repository apache/pulsar-client-go, pull requests merged in 2024-05, with the labels that each got.

#1212 [Improve] Add admin api GetListActiveBrokers
  pulsaradmin/pkg/admin/brokers.go
  pulsaradmin/pkg/admin/brokers_test.go
Labels: type/feature

#1213 [Improve] Add admin api ForceDeleteSchema
  pulsaradmin/pkg/admin/schema.go
  pulsaradmin/pkg/admin/schema_test.go
Labels: type/feature

#1214 [improve] Upgrade golang-jwt to v5
  go.mod
  go.sum
  oauth2/auth.go
Labels: dependencies

#1215 [Improve] Supplement schema admin api.
  pulsaradmin/pkg/admin/schema.go
  pulsaradmin/pkg/admin/schema_test.go
  pulsaradmin/pkg/utils/schema_util.go
Labels: type/feature

#1217 [fix] Return an error when AckCumulative on a Shared/KeyShared subscription
  pulsar/consumer_partition.go
  pulsar/consumer_test.go
Labels: type/bug

#1219 [Issue 1218][Reader] Reader Next returns on closed consumer
  pulsar/reader_impl.go
  pulsar/reader_test.go
  pulsar/table_view_impl.go
Labels: type/bug

#1220 [Improve] PIP-313 Support force unsubscribe using consumer api
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_multitopic_test.go
  pulsar/consumer_partition.go
  pulsar/consumer_regex.go
  pulsar/consumer_regex_test.go
  pulsar/consumer_test.go
  pulsar/internal/pulsar_proto/PulsarApi.pb.go
  pulsar/internal/pulsar_proto/PulsarApi.proto
  pulsar/internal/pulsartracing/consumer_interceptor_test.go
Labels: type/feature

#1221 [Improve] PIP-313 Add GetLastMessageIDs API
  pulsar/consumer.go
  pulsar/consumer_impl.go
  pulsar/consumer_multitopic.go
  pulsar/consumer_multitopic_test.go
  pulsar/consumer_regex.go
  pulsar/consumer_regex_test.go
  pulsar/consumer_test.go
  pulsar/impl_message.go
  pulsar/internal/pulsartracing/consumer_interceptor_test.go
  pulsar/message.go
Labels: type/feature
